import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer/Footer";
import { ToastContainer } from "react-toastify";
import React from "react";
import { Providers } from "./providers";
import { Toaster } from "react-hot-toast"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "المتميز للمعدات",
  description: "Generated by create next app",
};

interface IRootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: IRootLayoutProps) {
  return (
    <html lang="ar" dir="rtl">
      <head>
        {/* Add Google Fonts link */}
        <link
          href="https://fonts.googleapis.com/css2?family=Cairo:wght@400;600;700&display=swap"
          rel="stylesheet"
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
          <Providers>
            <Header />
            <Toaster position="bottom-left" toastOptions={{
              style: {
                background: "#e9e9e9",
                borderRadius: "5px",
                padding: "14px",
              }
            }}/>
            {/* <ToastContainer position="top-center" theme="colored" /> */}
            <main className="mt-20 container mx-auto px-4 py-4">
                {children}
            </main>
            <Footer />
          </Providers>
      </body>
    </html>
  );
}